//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIETMAUXE
    {
        public string MAXE { get; set; }
        public int IDMAU { get; set; }
        public int IDCHITIETXE { get; set; }
    }
}
