//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_XEMAY
    {
        public string MAXE { get; set; }
        public string TENXE { get; set; }
        public string MALOAI { get; set; }
        public string MANCC { get; set; }
        public string DUNGTICH { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<bool> DISABLE { get; set; }
    }
}
