//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEMAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XEMAY()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MAXE { get; set; }
        public string TENXE { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public string MAUSAC { get; set; }
        public string DUNGTICH { get; set; }
        public string TINHTRANG { get; set; }
        public string MALOAI { get; set; }
        public string MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
